### Dar de alta un titular (POST /api/titulares)
POST http://localhost:8080/api/titulares
Content-Type: application/json

{
  "numeroDocumento": "12345678",
  "nombre": "Juan",
  "apellido": "Pérez",
  "fechaNacimiento": "1990-05-15",
  "domicilio": "Calle Falsa 123",
  "grupoFactor": "A+",
  "donanteOrganos": true
}

### Intentar dar de alta un titular ya existente (debe devolver error 409)
POST http://localhost:8080/api/titulares
Content-Type: application/json

{
  "numeroDocumento": "12345678",
  "nombre": "Juan",
  "apellido": "Pérez",
  "fechaNacimiento": "1990-05-15",
  "domicilio": "Calle Falsa 123",
  "grupoFactor": "A+",
  "donanteOrganos": true
}

### Obtener titular por número de documento (GET /api/titulares/id/{numeroDocumento})
GET http://localhost:8080/api/titulares/id/12345678


### Emitir una licencia por primera vez (POST /api/licencias)
POST http://localhost:8080/api/licencias
Content-Type: application/json

{
  "documentoTitular": "12345678",
  "clases": "A",
  "observaciones": "Conduce con lentes de contacto"
}

### Emitir otra licencia para un mismo titular, sumando una clase (POST /api/licencias)
POST http://localhost:8080/api/licencias
Content-Type: application/json

{
  "documentoTitular": "12345678",
  "clases": "A B",
  "observaciones": "No conduce más con lentes de contacto, se curó"
}

### Buscar licencia activa por DNI (GET /api/licencias/{numeroDocumento})
GET http://localhost:8080/api/licencias/12345678

### Obtener comprobante de licencia por DNI (GET /api/licencias/comprobante/{numeroDocumento})
GET http://localhost:8080/api/licencias/comprobante/12345678