### 1. Dar de alta un titular (POST /api/titulares)
POST http://localhost:8080/api/titulares
Content-Type: application/json

{
  "numeroDocumento": "12345678",
  "nombre": "Juan",
  "apellido": "Pérez",
  "fechaNacimiento": "1990-05-15",
  "domicilio": "Calle Falsa 123",
  "grupoFactor": "A+",
  "donanteOrganos": true
}

### 2. Intentar dar de alta un titular ya existente (debe devolver error 409)
POST http://localhost:8080/api/titulares
Content-Type: application/json

{
  "numeroDocumento": "12345678",
  "nombre": "Juan",
  "apellido": "Pérez",
  "fechaNacimiento": "1990-05-15",
  "domicilio": "Calle Falsa 123",
  "grupoFactor": "A+",
  "donanteOrganos": true
}

### 3. Obtener titular por número de documento (GET /api/titulares/id/{numeroDocumento})
GET http://localhost:8080/api/titulares/id/12345678



### 4. Emitir una licencia (POST /api/licencias)
POST http://localhost:8080/api/licencias
Content-Type: application/json

{
  "documentoTitular": "12345678",
  "documentoUsuario": "11999888",
  "clases": "A B",
  "observaciones": "Conduce con lentes de contacto"
}

### 5. Buscar licencia activa por DNI (GET /api/licencias/{numeroDocumento})
GET http://localhost:8080/api/licencias/12345678

### 6. Obtener comprobante de licencia por DNI (GET /api/licencias/comprobante/{numeroDocumento})
GET http://localhost:8080/api/licencias/comprobante/12345678